# Generated by Django 5.0.3 on 2024-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=20)),
                ('flower_price', models.IntegerField()),
                ('flat_delivery_date', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('ON', 'ONLINE PAYMENT'), ('EMI', 'MONTHLY INSTALLMENT')], max_length=10)),
                ('flower_quantity', models.CharField(choices=[('10roses', '1booke'), ('20roses', '1booke'), ('30roses', '3booke')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
