# Generated by Django 5.0.3 on 2024-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_flower_delete_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='flat_delivery_date',
            field=models.CharField(max_length=10),
        ),
    ]
